export const opportunities = [
  {
    id: "web",
    title: "Développement web full stack",
    organization: "GOMYCODE",
    type: "Formation",
    location: "Agadir",
    duration: "6 mois",
    match: 92,
    image: "/user-portal/opp-web-dev.jpg",
    description:
      "Apprends à créer des applications web, construis ton portfolio et prépare ton premier stage.",
    skills: ["HTML & CSS", "JavaScript", "Travail en équipe"],
    deadline: "20 octobre 2026",
    details:
      "Formation en présentiel, du lundi au vendredi. Un accompagnement à la recherche de stage est inclus. Débutant accepté après un entretien de motivation.",
  },
  {
    id: "marketing",
    title: "Stage en marketing digital",
    organization: "StartUp Maroc",
    type: "Stage",
    location: "Casablanca",
    duration: "3 mois",
    match: 88,
    image: "/user-portal/opp-marketing.jpg",
    description:
      "Rejoins une équipe créative et développe tes compétences en communication et réseaux sociaux.",
    skills: ["Communication", "Réseaux sociaux", "Créativité"],
    deadline: "15 octobre 2026",
    details:
      "Stage encadré de trois mois. Une première expérience avec les réseaux sociaux est souhaitée. Les modalités de transport sont à discuter avec ton médiateur.",
  },
  {
    id: "retail",
    title: "Conseiller clientèle",
    organization: "Marjane",
    type: "Emploi",
    location: "Agadir",
    duration: "CDI",
    match: 85,
    image: "/user-portal/opp-retail.jpg",
    description:
      "Accueille et conseille les clients dans une équipe qui t’accompagne dès le premier jour.",
    skills: ["Relation client", "Organisation", "Français"],
    deadline: "25 octobre 2026",
    details:
      "Poste à temps plein avec formation à l’arrivée. Horaires variables. Prépare ton CV et échange avec ton médiateur avant de déposer ta candidature.",
  },
  {
    id: "enterprise",
    title: "Lance ton projet avec Injaz",
    organization: "INJAZ Maroc",
    type: "Programme",
    location: "En ligne",
    duration: "8 semaines",
    match: 82,
    image: "/user-portal/opp-entrepreneur.jpg",
    description:
      "Transforme ton idée en projet grâce à des ateliers pratiques et un mentor dédié.",
    skills: ["Entrepreneuriat", "Gestion", "Présentation"],
    deadline: "30 octobre 2026",
    details:
      "Ateliers en ligne deux fois par semaine. Le programme couvre la validation de l’idée, le budget et la présentation d’un projet. Accessible sans diplôme.",
  },
];
export const stories = [
  {
    id: "salma",
    name: "Salma",
    role: "Développeuse web",
    city: "Agadir",
    image: "/user-portal/story-salma.jpg",
    quote:
      "Je pensais que le numérique n’était pas pour moi. Aujourd’hui, j’en ai fait mon métier.",
    text: "Après une période sans emploi, Salma a commencé par un atelier de découverte. Avec l’aide de sa médiatrice, elle a rejoint une formation, créé son premier portfolio et trouvé un stage. Ce sont les petits objectifs chaque semaine qui l’ont aidée à garder confiance.",
  },
  {
    id: "omar",
    name: "Omar",
    role: "Entrepreneur",
    city: "Taroudant",
    image: "/user-portal/story-omar.jpg",
    quote:
      "Mon idée avait besoin d’un premier pas, et de quelqu’un qui y croyait.",
    text: "Omar souhaitait créer une petite activité locale. Un programme d’accompagnement lui a permis de tester son idée, comprendre ses coûts et rencontrer ses premiers clients. Son conseil : parler de son projet et demander de l’aide tôt.",
  },
  {
    id: "fatima",
    name: "Fatima",
    role: "Assistante RH",
    city: "Inezgane",
    image: "/user-portal/story-fatima.jpg",
    quote: "J’ai appris à parler de mes compétences avec confiance.",
    text: "Fatima a travaillé son CV et préparé ses entretiens avec son médiateur. Une immersion professionnelle lui a permis de découvrir les ressources humaines et de construire un projet qui lui ressemble.",
  },
  {
    id: "youssef",
    name: "Youssef",
    role: "Technicien",
    city: "Tiznit",
    image: "/user-portal/story-youssef.jpg",
    quote: "Une formation pratique m’a ouvert une nouvelle voie.",
    text: "Youssef a découvert la maintenance lors d’une visite de centre de formation. Il a choisi un parcours technique et a continué à rencontrer son médiateur pour organiser son transport et son stage.",
  },
];
export const youngPeople = [
  {
    id: "YE",
    name: "Yassine El Amrani",
    age: 22,
    city: "Agadir",
    stage: "Activé",
    trust: "Élevée",
    priority: "Suivi régulier",
    progress: 78,
    goal: "Formation en développement web",
    next: "Entretien d’orientation",
    date: "5 oct. · 10:00",
    photo: "/user-portal/story-khalid.jpg",
    skills: "Relation client, outils bureautiques",
    blocker: "CV à finaliser",
  },
  {
    id: "FZ",
    name: "Fatima Zahra A.",
    age: 19,
    city: "Inezgane",
    stage: "Orientation",
    trust: "Élevée",
    priority: "Suivi régulier",
    progress: 65,
    goal: "Stage en marketing digital",
    next: "Préparer un entretien",
    date: "5 oct. · 11:30",
    photo: "/user-portal/story-fatima.jpg",
    skills: "Communication, réseaux sociaux",
    blocker: "Transport à organiser",
  },
  {
    id: "OT",
    name: "Omar Tazi",
    age: 24,
    city: "Taroudant",
    stage: "Intégré",
    trust: "Élevée",
    priority: "Suivi régulier",
    progress: 92,
    goal: "Créer une activité locale",
    next: "Appel de suivi",
    date: "6 oct. · 09:00",
    photo: "/user-portal/story-omar.jpg",
    skills: "Entrepreneuriat, vente",
    blocker: "Aucun frein identifié",
  },
  {
    id: "SE",
    name: "Saima El Idrissi",
    age: 21,
    city: "Tiznit",
    stage: "Identifié",
    trust: "À renforcer",
    priority: "Prioritaire",
    progress: 32,
    goal: "Clarifier son projet",
    next: "Visite de proximité",
    date: "6 oct. · 14:00",
    photo: "/user-portal/story-salma.jpg",
    skills: "Créativité, organisation",
    blocker: "Contraintes familiales",
  },
  {
    id: "RD",
    name: "Rachid Daoudi",
    age: 23,
    city: "Tata",
    stage: "Identifié",
    trust: "À renforcer",
    priority: "Prioritaire",
    progress: 24,
    goal: "Découvrir les métiers techniques",
    next: "Reprendre contact",
    date: "7 oct. · 10:00",
    photo: "/user-portal/story-youssef.jpg",
    skills: "Travail manuel, mécanique",
    blocker: "Mobilité et distance",
  },
];
export const fieldActions = [
  {
    id: 1,
    title: "Un CV qui te ressemble",
    category: "Atelier",
    date: "7 octobre",
    time: "10:00 – 12:00",
    city: "Agadir",
    duration: "2 heures",
    description:
      "Mets en valeur tes compétences et repars avec une première version de ton CV.",
    icon: "file",
  },
  {
    id: 2,
    title: "Prépare ton premier entretien",
    category: "Coaching",
    date: "9 octobre",
    time: "14:00 – 15:00",
    city: "En ligne",
    duration: "1 heure",
    description:
      "Entraîne-toi avec un médiateur et découvre comment présenter ton parcours.",
    icon: "users",
  },
  {
    id: 3,
    title: "Découvre les métiers du numérique",
    category: "Découverte",
    date: "12 octobre",
    time: "09:00 – 11:00",
    city: "Inezgane",
    duration: "2 heures",
    description:
      "Rencontre des professionnels et découvre des parcours de formation accessibles.",
    icon: "compass",
  },
  {
    id: 4,
    title: "Fais le point sur tes envies",
    category: "À ton rythme",
    date: "Quand tu veux",
    time: "À ton rythme",
    city: "En ligne",
    duration: "15 minutes",
    description:
      "Identifie trois métiers qui t’intéressent et partage-les avec ton médiateur.",
    icon: "heart",
  },
];
